This configuration was Inspired by [[https://justinbarclay.ca/posts/from-zero-to-ide-with-emacs-and-lsp/][From Zero to IDE with Emacs and LSP]] but was complimented by other information found there and elsewhere and some changes of my own when necessary.

* General development oriented config

#+begin_src emacs-lisp
  ;; Number on columns when it makes sense
  (column-number-mode)
  (global-display-line-numbers-mode t)

  ;; Disable line numbers for some modes
  (dolist (mode '(org-mode-hook
		  term-mode-hook
		  shell-mode-hook
		  eshell-mode-hook))
    (add-hook mode (lambda () (display-line-numbers-mode 0))))

  ;; Paring delimiters (by colors and status line)
  (use-package rainbow-delimiters
    :hook (prog-mode . rainbow-delimiters-mode))

  ;; Allow common project editor configuration (~.editorconfig~)
  (use-package editorconfig
    :ensure t
    :config
    (editorconfig-mode 1))

  (use-package flymake
    :ensure t
    :hook (prog-mode . flymake-mode))

  ;; get env vars from shell
  ;; If this fails next time, may need to find a way to
  ;; (when (daemonp)
  ;; (exec-path-from-shell-initialize))
  ;; from inside use-package (need to learn morea about use-package :/
  (use-package exec-path-from-shell
    :commands (exec-path-from-shell)
    :ensure t)

  ;; completion via company mode
  (use-package company
    :ensure t
    :commands (global-company-mode)
    :init
    (global-company-mode)
    :custom
    (company-tooltip-align-annotations 't)
    (company-minimum-prefix-length 1)
    (company-idle-delay 0.1))
#+end_src


* Git

- [[https://magit.vc/][Magit]] is an awesome UI for git operations.
- [[https://magit.vc/manual/ghub/index.html#SEC_Contents][Forge]] is a package that enhances Magit to deal with GitHub operations.

#+begin_src emacs-lisp
  ;; Git via Magit!
  (use-package magit
    :ensure magit
    :custom
    (magit-display-buffer-function #'magit-display-buffer-same-window-except-diff-v1))

#+end_src


* Tree-Sitter Source Code Parsing library

See [[https://www.masteringemacs.org/article/how-to-get-started-tree-sitter][How to get Started with Tree-Sitter]]

To install the language grammars you must run the command ~treesit-install-language-grammar~ and select the language you want to install.

-EG: ~M-x treesit-install-language-grammar RET javascript RET~

#+begin_src emacs-lisp
  (setq treesit-language-source-alist
	'((bash "https://github.com/tree-sitter/tree-sitter-bash")
	  (cmake "https://github.com/uyha/tree-sitter-cmake")
	  (css "https://github.com/tree-sitter/tree-sitter-css")
	  (elisp "https://github.com/Wilfred/tree-sitter-elisp")
	  (go "https://github.com/tree-sitter/tree-sitter-go")
	  (html "https://github.com/tree-sitter/tree-sitter-html")
	  (javascript "https://github.com/tree-sitter/tree-sitter-javascript" "master" "src")
	  (json "https://github.com/tree-sitter/tree-sitter-json")
	  (make "https://github.com/alemuller/tree-sitter-make")
	  (markdown "https://github.com/ikatyang/tree-sitter-markdown")
	  (python "https://github.com/tree-sitter/tree-sitter-python")
	  (toml "https://github.com/tree-sitter/tree-sitter-toml")
	  (tsx "https://github.com/tree-sitter/tree-sitter-typescript" "master" "tsx/src")
	  (typescript "https://github.com/tree-sitter/tree-sitter-typescript" "master" "typescript/src")
	  (yaml "https://github.com/ikatyang/tree-sitter-yaml")))
#+end_src

But it may make sense to install them all, specially when there are dependencies.

The following will download and install all of the listed language grammars above.

However we keep it commented out to prevent doing it every time...

To re-run it, uncomment it and C-c-c to evaluate it.

#+begin_src emacs-lisp
; (mapc #'treesit-install-language-grammar (mapcar #'car treesit-language-source-alist))
#+end_src

| bash | cmake | css | elisp | go | html | javascript | json | make | markdown | python | toml | tsx | typescript | yaml |


* Javascript / Node

Config for the javascript-ts-mode

#+begin_src emacs-lisp
  (use-package js-ts-mode
    :ensure js-ts-mode
    :defer 't
    :mode "\\.js\\'"
    :custom
    (js-indent-level 2)
    :config
    (unbind-key "M-." js-base-mode-map)) ; unsure why yet
#+end_src

* TypeScript

Config for the typescript-ts-mode

#+begin_src emacs-lisp
  (use-package typescript-ts-mode
    :ensure typescript-ts-mode
    :defer 't
    :mode "\\.ts\\'"
    :custom
    (typescript-indent-level 2)
    :config
    (unbind-key "M-." typescript-ts-base-mode-map)) ; unsure why yet
#+end_src

* IntelliSense and More...

#+begin_src emacs-lisp
  (use-package eglot
     :hook (prog-mode . eglot-ensure)
     ;; The first 5 bindings aren't needed here, but are a good
     ;; reminder of what they are bound too
     :bind (("M-TAB" . completion-at-point)
	    ("M-g i" . imenu)
	    ("C-h ." . display-local-help)
	    ("M-." . xref-find-definitions)
	    ("M-," . xref-go-back)
	    :map
	    eglot-mode-map
	    ("C-c c a" . eglot-code-actions)
	    ("C-c c o" . eglot-code-actions-organize-imports)
	    ("C-c c r" . eglot-rename)
	    ("C-c c f" . eglot-format))
     :config)
#+end_src
